version: '3.9'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend Dockerfile
    image: cloudev.azurecr.io/frontend:latest  # Your frontend image from ACR
    ports:
      - "80:80"  # Expose port 80 externally (frontend entrypoint)

  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile
    image: cloudev.azurecr.io/backend:latest  # Your backend image from ACR
    ports:
      - "8000:8000"  # Expose port 8000 for backend service
