name: Azure Deployment

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # 1. Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Azure using Service Principal credentials
    - name: Login to Azure with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure AZURE_CREDENTIALS is set correctly

    # 3. Log in to Azure Container Registry (ACR) for Docker image push
    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io  # Use your ACR name from secrets
        username: ${{ secrets.ACR_USERNAME }}  # ACR username from secrets
        password: ${{ secrets.ACR_PASSWORD }}  # ACR password from secrets

    # 4. Build and push frontend image to ACR
    - name: Build and push frontend image
      run: |
        echo "Building frontend image"
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./frontend
        echo "Pushing frontend image"
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest  # Push the image to ACR

    # 5. Build and push backend image to ACR
    - name: Build and push backend image
      run: |
        echo "Building backend image"
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest ./backend
        echo "Pushing backend image"
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest  # Push the image to ACR

    # 6. Deploy the containers using Docker Compose to Azure App Service
    - name: Deploy to Azure App Service with Docker Compose
      run: |
        echo "Deploying to Azure App Service"
        set -x  # This will show every command that gets executed
        az webapp config container set \
          --name ${{ secrets.APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose-azure.yml \
          --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}  # Use the registry credentials from secrets
        set +x  # Turn off debug output after the command is run
